version: '3'
services:
  back:
    build: ./backend
    restart: on-failure
    volumes:
      - .:/back
    ports:
      - "5000:5000"
  front:
    build: ./frontend
    restart: on-failure
    volumes:
      - .:/front
    depends_on:
      - back
    ports:
      - "3000:3000"