version: '3'
services:
  back:
    build: ./backend
    restart: on-failure
#    env_file:
#      - .env
    volumes:
      - .:/back
  front:
    build: ./frontend
    restart: on-failure
#    env_file:
#      - .env
    environment:
      - PORT=3001
    volumes:
      - .:/front
    depends_on:
      - back
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - front
      - back
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SERVER_ROOT_URL=http://localhost/grafana/
    volumes:
      - grafana-data:/var/lib/grafana

volumes:
  grafana-data: