version: '3'
services:
  back:
    build: ./backend
    restart: on-failure
#    env_file:
#      - .env
    volumes:
      - .:/back
    ports:
      - "5000:5000"
  front:
    build: ./frontend
    restart: on-failure
    env_file:
      - .env
    volumes:
      - .:/front
    depends_on:
      - back
    ports:
      - "80:3000"