[mypy]
python_version = 3.12
strict = true
warn_return_any = True
warn_unused_configs = True
disallow_untyped_defs = True
disallow_incomplete_defs = True
check_untyped_defs = True

# Ignore V4 src/ for now (not yet typed)
[mypy-OpenHosta.*]
ignore_errors = True
