"""next_v5/openhosta — mirrors src/openhosta for guarded tests."""

from __future__ import annotations

from OpenHosta import (
    __version__,
    ask,
    ask_async,
    ask_stream,
    ask_stream_async,
    emulate,
    emulate_async,
    emulate_variants,
    closure,
    closure_async,
    gather_data,
    gather_data_async,
    config,
    reload_dotenv,
    Model,
    DefaultModel,
    DefaultPipeline,
    OpenAICompatibleModel,
    MetaPrompt,
    print_last_prompt,
    print_last_decoding,
    conversation,
    readable,
    markdown,
    print_last_probability_distribution,
    print_last_uncertainty,
    Pipeline,
    OneTurnConversationPipeline,
    safe,
    test,
    test_async,
    UncertaintyError,
    track_costs,
    register_audit_callback,
    unregister_audit_callback,
    AgentEngine,
    AgentSession,
    AgentStatus,
    tool,
    infer,
    playbook,
    planner,
    router,
    CapabilityRegistration,
    CapabilityDispatcher,
    Event,
    EventStream,
    EventType,
    TaskList,
    TaskStep,
    Healer,
    heal,
    GuardConfig,
    Principal,
    Roles,
    Authority,
    GuardedGuardConfig,
)

from OpenHosta.guarded.wrapper import (
    Guarded,
    GuardMetadata,
    guard,
    unguard,
    guard_info,
    guarded_to_python,
    guarded_to_json,
    guarded_to_markdown,
)

# All serialization functions imported from OpenHosta.guarded.wrapper above
