name: Deploy

on:
  push:
#    branches:
#      - master
  pull_request:
#    branches:
#      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Distribute app
      run: |
        mkdir -p app_package
        shopt -s extglob
        cp -R !(app_package) app_package
        tar czf app_package.tgz app_package
        rm -rf app_package


#        host: ${{ secrets.HOST }}
#        username: ${{ secrets.USERNAME }}
#        key: ${{ secrets.SSH_KEY }}

    - name: Deploy app
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        port: ${{ secrets.PORT }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        source: "app_package.tgz"
        target: ~/www/app_package.tgz

    - name: Clean up
      run: |
          rm -rf app