name: Python Quality Check

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[dev,pydantic]
          
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

  code-quality:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          
      - name: Install dependencies
        run: pip install .[dev]
        
      - name: Run autopep8
        run: python -m autopep8 --recursive --in-place src/OpenHosta
        
      - name: Run pyflakes
        run: python -m pyflakes src/OpenHosta/
        continue-on-error: true
        
      - name: Run isort
        run: python -m isort --check-only --diff src/OpenHosta
        continue-on-error: true

  static-analysis:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          
      - name: Install dependencies
        run: pip install .[dev]
        
      - name: Run mypy
        run: python -m mypy src/OpenHosta
        continue-on-error: true
        
      - name: Run pylint
        run: python -m pylint --rcfile=pyproject.toml src/OpenHosta
        continue-on-error: true
        
      - name: Run bandit
        run: python -m bandit -c pyproject.toml -r src/OpenHosta -f txt
        continue-on-error: true

  functionnal-tests:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          
      - name: Install dependencies
        run: pip install .[tests]

      - name: create .env file
        run: |
          echo "OPENHOSTA_DEFAULT_MODEL_API_KEY=${{ secrets.OPENHOSTA_DEFAULT_MODEL_API_KEY }}" >> .env

      - name: Run functionnal tests
        env:
          OPENHOSTA_DEFAULT_MODEL_API_KEY: ${{ secrets.OPENHOSTA_DEFAULT_MODEL_API_KEY }}         
        run: python -m pytest tests/functionnal -v --cov=OpenHosta

  notify:
    needs: [code-quality, static-analysis, functionnal-tests]
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Check for failures
        if: contains(needs.*.result, 'failure')
        run: |
          echo "Some jobs have failed. Check the logs above for more details."
          exit 1
